version: '2'

services:
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile-dev
    volumes:
      - ./keycloak/theme:/opt/jboss/keycloak/themes/openremote
    environment:
      TZ: "Europe/Zurich"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - "8081:8080"
  mongo:
    image: mongo:2.6
    command: --smallfiles
    environment:
        TZ: "Europe/Zurich"
  orion:
    image: fiware/orion:0.28
    links:
      - mongo
    ports:
      - "8082:1026"
    command: -dbhost mongo
    environment:
        TZ: "Europe/Zurich"
